import { query } from '../config/db.js';

/**
 * Enterprise AI Governance Service.
 * Implements strict version validation and approval registries for LLM prompts.
 */

/**
 * Registers a new prompt key category
 */
export async function registerPromptKey(key, name, description, tenantId) {
  const result = await query(
    `INSERT INTO prompt_registry (prompt_key, name, description, tenant_id)
     VALUES ($1, $2, $3, $4)
     ON CONFLICT (prompt_key) DO UPDATE SET 
       name = EXCLUDED.name,
       description = EXCLUDED.description
     RETURNING id`,
    [key, name, description, tenantId]
  );
  return result.rows[0].id;
}

/**
 * Submits a new version of a prompt for review
 */
export async function createPromptVersion(promptKey, templateText, versionTag, userId, tenantId) {
  let promptId = null;
  const regRes = await query('SELECT id FROM prompt_registry WHERE prompt_key = $1', [promptKey]);
  
  if (regRes.rows.length === 0) {
    promptId = await registerPromptKey(promptKey, promptKey.replace(/_/g, ' '), 'Autogenerated via registry upload', tenantId);
  } else {
    promptId = regRes.rows[0].id;
  }

  const result = await query(
    `INSERT INTO prompt_versions (prompt_id, version_tag, prompt_template, status, created_by, tenant_id)
     VALUES ($1, $2, $3, 'Review', $4, $5)
     RETURNING id`,
    [promptId, versionTag, templateText, userId, tenantId]
  );

  return result.rows[0].id;
}

/**
 * Approves a prompt version for production execution
 */
export async function approvePromptVersion(versionId, userId, tenantId) {
  // 1. Mark target version as Approved
  await query(
    `UPDATE prompt_versions 
     SET status = 'Approved', approved_by = $1, approved_at = CURRENT_TIMESTAMP 
     WHERE id = $2`,
    [userId, versionId]
  );

  // 2. Archive older approved versions of the same prompt
  const promptVersRes = await query('SELECT prompt_id FROM prompt_versions WHERE id = $1', [versionId]);
  const promptId = promptVersRes.rows[0]?.prompt_id;

  if (promptId) {
    await query(
      `UPDATE prompt_versions 
       SET status = 'Retired' 
       WHERE prompt_id = $1 AND id != $2 AND status = 'Approved'`,
      [promptId, versionId]
    );
  }

  return true;
}

/**
 * Retrieves the currently approved version of a prompt
 */
export async function getApprovedPrompt(promptKey, tenantId) {
  const result = await query(
    `SELECT pv.prompt_template, pv.version_tag FROM prompt_versions pv
     JOIN prompt_registry pr ON pv.prompt_id = pr.id
     WHERE pr.prompt_key = $1 AND pv.status = 'Approved'
     ORDER BY pv.approved_at DESC LIMIT 1`,
    [promptKey]
  );
  
  if (result.rows.length > 0) {
    return result.rows[0];
  }
  
  // Return null fallback, indicating that the developer template inside ragService will be used
  return null;
}
