apiVersion: v1
kind: Secret
metadata:
  name: clincommand-prod-secrets
  namespace: clincommand-production
type: Opaque
stringData:
  # Replace base64 or plaintext secrets here
  DATABASE_URL: "postgresql://postgres:YOUR_SECURE_PASSWORD@postgres-service.clincommand-production.svc.cluster.local:5432/clincommand"
  REDIS_URL: "redis://:YOUR_REDIS_PASSWORD@redis-service.clincommand-production.svc.cluster.local:6379"
  JWT_SECRET: "YOUR_JWT_SECRET_SIGNING_KEY"
  NODE_ENV: "production"
  PORT: "8000"
